//! All clientbound packets and methods to read them

const std = @import("std");
const net = @import("net.zig");
const string = @import("string.zig");
const Packets = @import("packets.zig").Packets;

/// Packet throwing an error when attempting to interpret
fn ErrorPacket(comptime err: anyerror) type {
    return struct {
        pub fn receive(_: std.mem.Allocator, _: *std.Io.Reader) !@This() {
            return err;
        }
    };
}

/// Illegal packet
const BadPacket = ErrorPacket(error.BadPacket);
/// Unimplemented packet
const UnimplementedPacket = ErrorPacket(error.Unimplemented);

/// Debug packet that prints some amount of data and then throws an error
fn PacketDebug(size: comptime_int) type {
    return struct {
        pub fn receive(_: std.mem.Allocator, stream: *std.Io.Reader) !@This() {
            var buf: [size]u8 = undefined;
            try stream.readSliceAll(&buf);

            std.debug.print("Packet dump:\n{any}\n", .{&buf});

            return error.BadPacket;
        }
    };
}

/// Union of any inbound packet
pub const InboundPacket = union(Packets) {
    keep_alive_0: @import("client_bound/Packet0KeepAlive.zig"),
    login_1: @import("client_bound/Packet1Login.zig"),
    handshake_2: @import("client_bound/Packet2Handshake.zig"),
    chat_3: @import("client_bound/Packet3Chat.zig"),
    update_time_4: @import("client_bound/Packet4UpdateTime.zig"),
    player_inventory_5: UnimplementedPacket,
    spawn_position_6: @import("client_bound/Packet6SpawnPosition.zig"),
    use_entity_7: UnimplementedPacket,
    update_health_8: UnimplementedPacket,
    respawn_9: UnimplementedPacket,
    flying_10: UnimplementedPacket,
    player_position_11: UnimplementedPacket,
    player_look_12: UnimplementedPacket,
    player_look_move_13: @import("client_bound/Packet13PlayerLookMove.zig"),
    block_dig_14: UnimplementedPacket,
    place_15: UnimplementedPacket,
    block_item_switch_16: UnimplementedPacket,
    sleep_17: UnimplementedPacket,
    animation_18: UnimplementedPacket,
    entity_action_19: UnimplementedPacket,
    named_entity_spawn_20: UnimplementedPacket,
    pickup_spawn_21: @import("client_bound/Packet21PickupSpawn.zig"),
    collect_22: UnimplementedPacket,
    vehicle_spawn_23: UnimplementedPacket,
    mob_spawn_24: @import("client_bound/Packet24MobSpawn.zig"),
    entity_painting_25: UnimplementedPacket,
    unused_26: BadPacket,
    position_27: UnimplementedPacket,
    entity_velocity_28: @import("client_bound/Packet28EntityVelocity.zig"),
    destroy_entity_29: UnimplementedPacket,
    entity_30: UnimplementedPacket,
    rel_entity_move_31: @import("client_bound/Packet31RelEntityMove.zig"),
    entity_look_32: UnimplementedPacket,
    rel_entity_move_look_33: @import("client_bound/Packet33RelEntityMoveLook.zig"),
    entity_teleport_34: UnimplementedPacket,
    unused_35: BadPacket,
    unused_36: BadPacket,
    unused_37: BadPacket,
    entity_status_38: UnimplementedPacket,
    attach_entity_39: UnimplementedPacket,
    entity_metadata_40: UnimplementedPacket,
    unused_41: BadPacket,
    unused_42: BadPacket,
    unused_43: BadPacket,
    unused_44: BadPacket,
    unused_45: BadPacket,
    unused_46: BadPacket,
    unused_47: BadPacket,
    unused_48: BadPacket,
    unused_49: BadPacket,
    pre_chunk_50: @import("client_bound/Packet50PreChunk.zig"),
    map_chunk_51: UnimplementedPacket,
    multi_block_change_52: UnimplementedPacket,
    block_change_53: UnimplementedPacket,
    play_note_block_54: UnimplementedPacket,
    unused_55: BadPacket,
    unused_56: BadPacket,
    unused_57: BadPacket,
    unused_58: BadPacket,
    unused_59: BadPacket,
    explosion_60: UnimplementedPacket,
    door_change_61: UnimplementedPacket,
    unused_62: BadPacket,
    unused_63: BadPacket,
    unused_64: BadPacket,
    unused_65: BadPacket,
    unused_66: BadPacket,
    unused_67: BadPacket,
    unused_68: BadPacket,
    unused_69: BadPacket,
    bed_70: @import("client_bound/Packet70Bed.zig"),
    weather_71: UnimplementedPacket,
    unused_72: BadPacket,
    unused_73: BadPacket,
    unused_74: BadPacket,
    unused_75: BadPacket,
    unused_76: BadPacket,
    unused_77: BadPacket,
    unused_78: BadPacket,
    unused_79: BadPacket,
    unused_80: BadPacket,
    unused_81: BadPacket,
    unused_82: BadPacket,
    unused_83: BadPacket,
    unused_84: BadPacket,
    unused_85: BadPacket,
    unused_86: BadPacket,
    unused_87: BadPacket,
    unused_88: BadPacket,
    unused_89: BadPacket,
    unused_90: BadPacket,
    unused_91: BadPacket,
    unused_92: BadPacket,
    unused_93: BadPacket,
    unused_94: BadPacket,
    unused_95: BadPacket,
    unused_96: BadPacket,
    unused_97: BadPacket,
    unused_98: BadPacket,
    unused_99: BadPacket,
    open_window_100: UnimplementedPacket,
    close_window_101: UnimplementedPacket,
    window_click_102: UnimplementedPacket,
    set_slot_103: @import("client_bound/Packet103SetSlot.zig"),
    window_items_104: @import("client_bound/Packet104WindowItems.zig"),
    update_progress_bar_105: UnimplementedPacket,
    transaction_106: UnimplementedPacket,
    unused_107: BadPacket,
    unused_108: BadPacket,
    unused_109: BadPacket,
    unused_110: BadPacket,
    unused_111: BadPacket,
    unused_112: BadPacket,
    unused_113: BadPacket,
    unused_114: BadPacket,
    unused_115: BadPacket,
    unused_116: BadPacket,
    unused_117: BadPacket,
    unused_118: BadPacket,
    unused_119: BadPacket,
    unused_120: BadPacket,
    unused_121: BadPacket,
    unused_122: BadPacket,
    unused_123: BadPacket,
    unused_124: BadPacket,
    unused_125: BadPacket,
    unused_126: BadPacket,
    unused_127: BadPacket,
    unused_128: BadPacket,
    unused_129: BadPacket,
    update_sign_130: UnimplementedPacket,
    map_data_131: UnimplementedPacket,
    unused_132: BadPacket,
    unused_133: BadPacket,
    unused_134: BadPacket,
    unused_135: BadPacket,
    unused_136: BadPacket,
    unused_137: BadPacket,
    unused_138: BadPacket,
    unused_139: BadPacket,
    unused_140: BadPacket,
    unused_141: BadPacket,
    unused_142: BadPacket,
    unused_143: BadPacket,
    unused_144: BadPacket,
    unused_145: BadPacket,
    unused_146: BadPacket,
    unused_147: BadPacket,
    unused_148: BadPacket,
    unused_149: BadPacket,
    unused_150: BadPacket,
    unused_151: BadPacket,
    unused_152: BadPacket,
    unused_153: BadPacket,
    unused_154: BadPacket,
    unused_155: BadPacket,
    unused_156: BadPacket,
    unused_157: BadPacket,
    unused_158: BadPacket,
    unused_159: BadPacket,
    unused_160: BadPacket,
    unused_161: BadPacket,
    unused_162: BadPacket,
    unused_163: BadPacket,
    unused_164: BadPacket,
    unused_165: BadPacket,
    unused_166: BadPacket,
    unused_167: BadPacket,
    unused_168: BadPacket,
    unused_169: BadPacket,
    unused_170: BadPacket,
    unused_171: BadPacket,
    unused_172: BadPacket,
    unused_173: BadPacket,
    unused_174: BadPacket,
    unused_175: BadPacket,
    unused_176: BadPacket,
    unused_177: BadPacket,
    unused_178: BadPacket,
    unused_179: BadPacket,
    unused_180: BadPacket,
    unused_181: BadPacket,
    unused_182: BadPacket,
    unused_183: BadPacket,
    unused_184: BadPacket,
    unused_185: BadPacket,
    unused_186: BadPacket,
    unused_187: BadPacket,
    unused_188: BadPacket,
    unused_189: BadPacket,
    unused_190: BadPacket,
    unused_191: BadPacket,
    unused_192: BadPacket,
    unused_193: BadPacket,
    unused_194: BadPacket,
    unused_195: BadPacket,
    unused_196: BadPacket,
    unused_197: BadPacket,
    unused_198: BadPacket,
    unused_199: BadPacket,
    statistic_200: UnimplementedPacket,
    unused_201: BadPacket,
    unused_202: BadPacket,
    unused_203: BadPacket,
    unused_204: BadPacket,
    unused_205: BadPacket,
    unused_206: BadPacket,
    unused_207: BadPacket,
    unused_208: BadPacket,
    unused_209: BadPacket,
    unused_210: BadPacket,
    unused_211: BadPacket,
    unused_212: BadPacket,
    unused_213: BadPacket,
    unused_214: BadPacket,
    unused_215: BadPacket,
    unused_216: BadPacket,
    unused_217: BadPacket,
    unused_218: BadPacket,
    unused_219: BadPacket,
    unused_220: BadPacket,
    unused_221: BadPacket,
    unused_222: BadPacket,
    unused_223: BadPacket,
    unused_224: BadPacket,
    unused_225: BadPacket,
    unused_226: BadPacket,
    unused_227: BadPacket,
    unused_228: BadPacket,
    unused_229: BadPacket,
    unused_230: BadPacket,
    unused_231: BadPacket,
    unused_232: BadPacket,
    unused_233: BadPacket,
    unused_234: BadPacket,
    unused_235: BadPacket,
    unused_236: BadPacket,
    unused_237: BadPacket,
    unused_238: BadPacket,
    unused_239: BadPacket,
    unused_240: BadPacket,
    unused_241: BadPacket,
    unused_242: BadPacket,
    unused_243: BadPacket,
    unused_244: BadPacket,
    unused_245: BadPacket,
    unused_246: BadPacket,
    unused_247: BadPacket,
    unused_248: BadPacket,
    unused_249: BadPacket,
    unused_250: BadPacket,
    unused_251: BadPacket,
    unused_252: BadPacket,
    unused_253: BadPacket,
    unused_254: BadPacket,
    kick_disconnect_255: @import("client_bound/Packet255KickDisconnect.zig"),
};
