//! All clientbound packets and methods to read them

const std = @import("std");
const string = @import("string.zig");

pub const BadPacket = struct {
    pub fn receive(_: *std.Io.Reader) !@This() {
        return error.BadPacket;
    }
};

pub const Packet1Login = struct {
    protocol_version: i32,
    username: []const u8,
    map_seed: i64,
    dimension: i8,

    pub fn receive(_: *std.Io.Reader) !@This() {
        return error.Unimplemented;
    }
};

pub const Packet2Handshake = struct {
    username: []const u8,

    pub fn receive(stream: *std.Io.Reader) !@This() {
        // TEMPORARY (TODO)
        var buf: [128]u8 = undefined;
        var fba = std.heap.FixedBufferAllocator.init(&buf);
        const alloc = fba.allocator();
        const name = try string.readString(stream, alloc);
        std.debug.print("Handshake: \"{s}\"\n", .{name});
        return undefined;
    }
};

// List of all packet classes to retrieve them via a comptime ID (grouped by 16)
pub const packet_by_id = [256]type{
    // 0
    BadPacket,
    Packet1Login,
    Packet2Handshake,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 16
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 32
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 48
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 64
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 80
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 96
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 112
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 128
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 144
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 160
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 176
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 192
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 208
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 224
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 240
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    BadPacket,
    // 256
};
