//! All serverbound packets and methods to write them

const std = @import("std");
const net = @import("net.zig");
const Packets = @import("packets.zig").Packets;

pub const Packet0KeepAlive = @import("server_bound/Packet0KeepAlive.zig");
pub const Packet1Login = @import("server_bound/Packet1Login.zig");
pub const Packet2Handshake = @import("server_bound/Packet2Handshake.zig");

pub const OutboundPacket = union(Packets) {
    /// Send the packet
    pub fn send(self: @This(), stream: *std.Io.Writer) !void {
        // Packet ID
        try stream.writeByte(@intFromEnum(std.meta.activeTag(self)));
        // Payload
        switch (self) {
            inline else => |payload| {
                const PayloadT = @TypeOf(payload);
                if (PayloadT != void and @hasDecl(PayloadT, "send")) {
                    try payload.send(stream);
                } else {
                    std.debug.print("No send function for queued packet!\n", .{});
                }
            },
        }
        // TODO: should this be done here?
        try stream.flush();
    }

    pub fn encapsulate(packet: anytype) OutboundPacket {
        return @unionInit(@This(), @tagName(@TypeOf(packet).tag), packet);
    }

    //
    keep_alive_0: Packet0KeepAlive,
    login_1: Packet1Login,
    handshake_2: Packet2Handshake,
    chat_3: void,
    update_time_4: void,
    player_inventory_5: void,
    spawn_position_6: void,
    use_entity_7: void,
    update_health_8: void,
    respawn_9: void,
    flying_10: void,
    player_position_11: void,
    player_look_12: void,
    player_look_move_13: void,
    block_dig_14: void,
    place_15: void,
    block_item_switch_16: void,
    sleep_17: void,
    animation_18: void,
    entity_action_19: void,
    named_entity_spawn_20: void,
    pickup_spawn_21: void,
    collect_22: void,
    inanimate_spawn_23: void,
    mob_spawn_24: void,
    entity_painting_25: void,
    //
    unused_26: void,
    //
    position_27: void,
    entity_velocity_28: void,
    destroy_entity_29: void,
    entity_30: void,
    rel_entity_move_31: void,
    entity_look_32: void,
    rel_entity_move_look_33: void,
    entity_teleport_34: void,
    //
    unused_35: void,
    unused_36: void,
    unused_37: void,
    //
    entity_status_38: void,
    attach_entity_39: void,
    entity_metadata_40: void,
    //
    unused_41: void,
    unused_42: void,
    unused_43: void,
    unused_44: void,
    unused_45: void,
    unused_46: void,
    unused_47: void,
    unused_48: void,
    unused_49: void,
    //
    pre_chunk_50: void,
    map_chunk_51: void,
    multi_block_change_52: void,
    block_change_53: void,
    play_note_block_54: void,
    //
    unused_55: void,
    unused_56: void,
    unused_57: void,
    unused_58: void,
    unused_59: void,
    //
    explosion_60: void,
    particle_effect_61: void,
    //
    unused_62: void,
    unused_63: void,
    unused_64: void,
    unused_65: void,
    unused_66: void,
    unused_67: void,
    unused_68: void,
    unused_69: void,
    //
    bed_70: void,
    weather_71: void,
    //
    unused_72: void,
    unused_73: void,
    unused_74: void,
    unused_75: void,
    unused_76: void,
    unused_77: void,
    unused_78: void,
    unused_79: void,
    unused_80: void,
    unused_81: void,
    unused_82: void,
    unused_83: void,
    unused_84: void,
    unused_85: void,
    unused_86: void,
    unused_87: void,
    unused_88: void,
    unused_89: void,
    unused_90: void,
    unused_91: void,
    unused_92: void,
    unused_93: void,
    unused_94: void,
    unused_95: void,
    unused_96: void,
    unused_97: void,
    unused_98: void,
    unused_99: void,
    //
    open_window_100: void,
    close_window_101: void,
    window_click_102: void,
    set_slot_103: void,
    window_items_104: void,
    update_progress_bar_105: void,
    transaction_106: void,
    //
    unused_107: void,
    unused_108: void,
    unused_109: void,
    unused_110: void,
    unused_111: void,
    unused_112: void,
    unused_113: void,
    unused_114: void,
    unused_115: void,
    unused_116: void,
    unused_117: void,
    unused_118: void,
    unused_119: void,
    unused_120: void,
    unused_121: void,
    unused_122: void,
    unused_123: void,
    unused_124: void,
    unused_125: void,
    unused_126: void,
    unused_127: void,
    unused_128: void,
    unused_129: void,
    //
    update_sign_130: void,
    map_data_131: void,
    //
    unused_132: void,
    unused_133: void,
    unused_134: void,
    unused_135: void,
    unused_136: void,
    unused_137: void,
    unused_138: void,
    unused_139: void,
    unused_140: void,
    unused_141: void,
    unused_142: void,
    unused_143: void,
    unused_144: void,
    unused_145: void,
    unused_146: void,
    unused_147: void,
    unused_148: void,
    unused_149: void,
    unused_150: void,
    unused_151: void,
    unused_152: void,
    unused_153: void,
    unused_154: void,
    unused_155: void,
    unused_156: void,
    unused_157: void,
    unused_158: void,
    unused_159: void,
    unused_160: void,
    unused_161: void,
    unused_162: void,
    unused_163: void,
    unused_164: void,
    unused_165: void,
    unused_166: void,
    unused_167: void,
    unused_168: void,
    unused_169: void,
    unused_170: void,
    unused_171: void,
    unused_172: void,
    unused_173: void,
    unused_174: void,
    unused_175: void,
    unused_176: void,
    unused_177: void,
    unused_178: void,
    unused_179: void,
    unused_180: void,
    unused_181: void,
    unused_182: void,
    unused_183: void,
    unused_184: void,
    unused_185: void,
    unused_186: void,
    unused_187: void,
    unused_188: void,
    unused_189: void,
    unused_190: void,
    unused_191: void,
    unused_192: void,
    unused_193: void,
    unused_194: void,
    unused_195: void,
    unused_196: void,
    unused_197: void,
    unused_198: void,
    unused_199: void,
    //
    statistic_200: void,
    //
    unused_201: void,
    unused_202: void,
    unused_203: void,
    unused_204: void,
    unused_205: void,
    unused_206: void,
    unused_207: void,
    unused_208: void,
    unused_209: void,
    unused_210: void,
    unused_211: void,
    unused_212: void,
    unused_213: void,
    unused_214: void,
    unused_215: void,
    unused_216: void,
    unused_217: void,
    unused_218: void,
    unused_219: void,
    unused_220: void,
    unused_221: void,
    unused_222: void,
    unused_223: void,
    unused_224: void,
    unused_225: void,
    unused_226: void,
    unused_227: void,
    unused_228: void,
    unused_229: void,
    unused_230: void,
    unused_231: void,
    unused_232: void,
    unused_233: void,
    unused_234: void,
    unused_235: void,
    unused_236: void,
    unused_237: void,
    unused_238: void,
    unused_239: void,
    unused_240: void,
    unused_241: void,
    unused_242: void,
    unused_243: void,
    unused_244: void,
    unused_245: void,
    unused_246: void,
    unused_247: void,
    unused_248: void,
    unused_249: void,
    unused_250: void,
    unused_251: void,
    unused_252: void,
    unused_253: void,
    unused_254: void,
    //
    kick_disconnect_255: void,
};
