//! List of all existing blocks

const std = @import("std");

const Block = @import("Block.zig");

pub const models = @import("block_models.zig");
pub const Context = @import("context.zig").Context;
pub const uv = @import("uv.zig");

fn texpos(x: comptime_int, y: comptime_int) comptime_int {
    return y * 16 + x;
}

// TODO: Struct containing all block ids by name as decls for comptime

/// Table of all block types
pub const table = [256]Block{
    // 0
    .{ .name = "air", .full_block = false },
    .{ .name = "stone", .tex_id = 1 },
    .{ .name = "grass", .tex_id = 3, .top_tex_id = 0, .bottom_tex_id = 2, .uv_type = .barrel },
    .{ .name = "dirt", .tex_id = 2 },
    .{ .name = "cobblestone", .tex_id = texpos(0, 1) },
    .{ .name = "wood", .tex_id = 4 },
    .{ .name = "sapling", .tex_id = 15, .full_block = false },
    .{ .name = "bedrock", .tex_id = texpos(1, 1) },
    .{ .name = "water", .tex_id = texpos(15, 12), .full_block = false },
    .{ .name = "water", .tex_id = texpos(15, 12), .full_block = false },
    .{ .name = "lava", .tex_id = texpos(15, 14), .full_block = false },
    .{ .name = "lava", .tex_id = texpos(15, 14), .full_block = false },
    .{ .name = "sand", .tex_id = texpos(2, 1) },
    .{ .name = "gravel", .tex_id = texpos(3, 1) },
    .{ .name = "oreGold", .tex_id = texpos(0, 2) },
    .{ .name = "oreIron", .tex_id = texpos(1, 2) },
    // 16
    .{ .name = "oreCoal", .tex_id = texpos(2, 2) },
    .{ .name = "log", .tex_id = texpos(4, 1), .top_tex_id = texpos(5, 1), .bottom_tex_id = texpos(5, 1), .uv_type = .barrel },
    .{ .name = "leaves", .tex_id = texpos(4, 3), .full_block = false },
    .{},
    .{ .name = "glass", .tex_id = texpos(1, 3), .full_block = false },
    .{ .name = "oreLapis", .tex_id = texpos(0, 10) },
    .{},
    .{},
    .{ .name = "sandStone", .tex_id = texpos(0, 12), .top_tex_id = texpos(0, 11), .bottom_tex_id = texpos(0, 13), .uv_type = .barrel },
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "tallgrass", .tex_id = texpos(7, 2), .full_block = false, .block_model = .plant, .uv_type = .plant },
    // 32
    .{ .name = "deadbush", .tex_id = texpos(7, 3), .full_block = false, .block_model = .plant, .uv_type = .plant },
    .{},
    .{},
    .{},
    .{},
    .{ .name = "flower", .tex_id = 13, .full_block = false, .block_model = .plant, .uv_type = .plant },
    .{ .name = "rose", .tex_id = 12, .full_block = false, .block_model = .plant, .uv_type = .plant },
    .{ .name = "mushroom", .tex_id = texpos(1, 13), .full_block = false, .block_model = .plant, .uv_type = .plant },
    .{ .name = "mushroom", .tex_id = texpos(1, 12), .full_block = false, .block_model = .plant, .uv_type = .plant },
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 48
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "oreDiamond", .tex_id = texpos(2, 3) },
    .{},
    .{ .name = "workbench", .tex_id = texpos(12, 3), .east_tex_id = texpos(11, 3), .south_tex_id = texpos(11, 3), .west_tex_id = texpos(12, 3), .top_tex_id = texpos(11, 2), .bottom_tex_id = 4, .uv_type = .advanced },
    .{},
    .{},
    .{},
    .{},
    .{},
    // 64
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "oreRedstone", .tex_id = texpos(3, 3) },
    .{ .name = "oreRedstone", .tex_id = texpos(3, 3) },
    .{},
    .{},
    .{},
    .{},
    .{},
    // 80
    .{},
    .{ .name = "cactus", .tex_id = texpos(6, 4), .full_block = false },
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 96
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 112
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 128
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 144
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 160
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 176
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 192
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 208
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 224
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 240
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 256
};
