//! List of all existing blocks

const Block = @import("Block.zig");

pub const models = @import("block_models.zig");
pub const Context = @import("context.zig").Context;
pub const uv = @import("uv.zig");

fn texpos(x: comptime_int, y: comptime_int) comptime_int {
    return y * 16 + x;
}

/// Table of all block types
pub const table = [256]Block{
    // 0
    .{ .name = "air", .full_block = false },
    .{ .name = "stone", .tex_id = 1 },
    .{ .name = "grass", .tex_id = 3, .top_tex_id = 0, .bottom_tex_id = 0, .uv_type = .barrel },
    .{ .name = "dirt", .tex_id = 2 },
    .{ .name = "cobblestone", .tex_id = texpos(0, 1) },
    .{ .name = "planks", .tex_id = 4 },
    .{ .name = "sapling", .tex_id = 15, .full_block = false },
    .{ .name = "bedrock", .tex_id = texpos(1, 1) },
    .{ .name = "water_moving", .tex_id = texpos(15, 12), .full_block = false },
    .{ .name = "water_still", .tex_id = texpos(15, 12), .full_block = false },
    .{ .name = "lava_moving", .tex_id = texpos(15, 14), .full_block = false },
    .{ .name = "lava_still", .tex_id = texpos(15, 14), .full_block = false },
    .{ .name = "sand", .tex_id = texpos(2, 1) },
    .{ .name = "gravel", .tex_id = texpos(3, 1) },
    .{ .name = "ore_gold", .tex_id = texpos(0, 2) },
    .{ .name = "ore_iron", .tex_id = texpos(1, 2) },
    // 16
    .{ .name = "ore_coal", .tex_id = texpos(2, 2) },
    .{ .name = "wood", .tex_id = texpos(4, 1), .top_tex_id = texpos(5, 1), .bottom_tex_id = texpos(5, 1), .uv_type = .barrel },
    .{ .name = "leaves", .tex_id = texpos(4, 3), .full_block = false },
    .{},
    .{},
    .{ .name = "ore_lapis", .tex_id = texpos(0, 10) },
    .{},
    .{},
    .{ .name = "sandstone", .tex_id = texpos(0, 12), .top_tex_id = texpos(0, 11), .bottom_tex_id = texpos(0, 13), .uv_type = .barrel },
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "tallgrass", .tex_id = texpos(7, 2), .full_block = false },
    // 32
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 48
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "ore_diamond", .tex_id = texpos(2, 3) },
    .{},
    .{ .name = "workbench", .tex_id = texpos(12, 3), .east_tex_id = texpos(11, 3), .south_tex_id = texpos(11, 3), .west_tex_id = texpos(12, 3), .top_tex_id = texpos(11, 2), .bottom_tex_id = 4, .uv_type = .advanced },
    .{},
    .{},
    .{},
    .{},
    .{},
    // 64
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{ .name = "ore_redstone", .tex_id = texpos(3, 3) },
    .{ .name = "ore_redstone_glowing", .tex_id = texpos(3, 3) },
    .{},
    .{},
    .{},
    .{},
    .{},
    // 80
    .{},
    .{ .name = "cactus", .tex_id = texpos(6, 4), .full_block = false },
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 96
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 112
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 128
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 144
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 160
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 176
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 192
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 208
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 224
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 240
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    .{},
    // 256
};
